DROP TABLE IF EXISTS `meto`.`profiles`;
CREATE TABLE  `meto`.`profiles` (
  `dateTime` datetime NOT NULL default '0000-00-00 00:00:00',
  `e2pZone1Sv` double default NULL,
  `e2pZone2Sv` double default NULL,
  `e2pZone3Sv` double default NULL,
  `e2pZone4Sv` double default NULL,
  `e2pTraceSv` double default NULL,
  `e2kZone1Sv` double default NULL,
  `e2kZone2Sv` double default NULL,
  `e2kZone3Sv` double default NULL,
  `e2kTraceSv` double default NULL,
  `e3kZone1Sv` double default NULL,
  `e3kZone2Sv` double default NULL,
  `e3kZone3Sv` double default NULL,
  `e3kTraceSv` double default NULL,
  `e3pZone1Sv` double default NULL,
  `e3pZone2Sv` double default NULL,
  `e3pZone3Sv` double default NULL,
  `e3pZone4Sv` double default NULL,
  `e3pTraceSv` double default NULL,
  `e3mZone1Sv` double default NULL,
  `e3mZone2Sv` double default NULL,
  `e3mZone3Sv` double default NULL,
  `e3mTraceSv` double default NULL,
  `sgZone1Sv` double default NULL,
  `sgZone2Sv` double default NULL,
  `e2pRotate` double default NULL,
  `e2kRotate` double default NULL,
  `e3kRotate` double default NULL,
  `e3pRotate` double default NULL,
  `e3mRotate` double default NULL,
  `sgRotate` double default NULL,
  `tuSpeed` double default NULL,
  `sgDiameter` double default NULL,
  `name` varchar(45) NOT NULL,
  PRIMARY KEY  (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=cp1251;